### ISSUE TITLE
chromium doesn't exist

### ISSUE THREAD

**Issue by cloudlena** [charleskorn/raspi-information-radiator#1]
When I run this role, I get:

```
failed: [ops1] => (item=[u'matchbox', u'x11-xserver-utils', u'ttf-mscorefonts-installer', u'sqlite3', u'libnss3', u'screen', u'unclutter', u'chromium']) => {"failed": true, "item": ["matchbox", "x11-xserver-utils", "ttf-mscorefonts-installer", "sqlite3", "libnss3", "screen", "unclutter", "chromium"], "msg": "No package matching 'chromium' is available"}
```

**Comment by charleskorn** [comment]
That's strange... if you try running `sudo apt-get install chromium` from the command line, what do you get?

**Comment by martbhell** [comment]
chromium-browser is not available in the Jessie (and based on my googling it's not easy to install on an RPi1 either). I got this role working my my RPi1 with Wheezy.

**Comment by charleskorn** [comment]
Thanks for that @martbhell, I'll add that to the readme.
